"""Add date_added to Todo model

Revision ID: e48765a96fc9
Revises: 60437ebcdc99
Create Date: 2022-05-29 11:29:16.029811

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'e48765a96fc9'
down_revision = '60437ebcdc99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
